# Generated by Django 5.1.1 on 2024-12-04 08:29

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, db_comment='企业名称', max_length=255, null=True, verbose_name='企业名称')),
                ('company_type', models.CharField(blank=True, db_comment='企业类型', max_length=100, null=True, verbose_name='企业类型')),
                ('company_location', models.CharField(blank=True, db_comment='企业归属地', max_length=255, null=True, verbose_name='企业归属地')),
                ('license_type', models.CharField(blank=True, db_comment='办照类型', max_length=100, null=True, verbose_name='办照类型')),
                ('license_fee', models.IntegerField(blank=True, db_comment='办照费用', null=True, verbose_name='办照费用')),
                ('one_time_address_fee', models.IntegerField(blank=True, db_comment='一次性地址费', null=True, verbose_name='一次性地址费')),
                ('brand_fee', models.IntegerField(blank=True, db_comment='牌子费', null=True, verbose_name='牌子费')),
                ('seal_fee', models.IntegerField(blank=True, db_comment='刻章费', null=True, verbose_name='刻章费')),
                ('agency_type', models.CharField(blank=True, db_comment='代理类型', max_length=100, null=True, verbose_name='代理类型')),
                ('agency_fee', models.IntegerField(blank=True, db_comment='代理费', null=True, verbose_name='代理费')),
                ('accounting_software_fee', models.IntegerField(blank=True, db_comment='记账软件费', null=True, verbose_name='记账软件费')),
                ('address_fee', models.IntegerField(blank=True, db_comment='地址费', null=True, verbose_name='地址费')),
                ('agency_start_date', models.DateField(blank=True, db_comment='代理开始日期', null=True, verbose_name='代理开始日期')),
                ('agency_end_date', models.DateField(blank=True, db_comment='代理结束日期', null=True, verbose_name='代理结束日期')),
                ('business_type', models.CharField(blank=True, db_comment='业务类型', max_length=100, null=True, verbose_name='业务类型')),
                ('contract_type', models.CharField(blank=True, db_comment='合同类型', max_length=100, null=True, verbose_name='合同类型')),
                ('contract_image', models.CharField(blank=True, db_comment='合同图片', max_length=255, null=True, verbose_name='合同图片')),
                ('invoice_software_provider', models.CharField(blank=True, db_comment='开票软件服务商', max_length=255, null=True, verbose_name='开票软件服务商')),
                ('invoice_software_fee', models.IntegerField(blank=True, db_comment='开票软件费', null=True, verbose_name='开票软件费')),
                ('invoice_software_start_date', models.DateField(blank=True, db_comment='开票软件开始日期', null=True, verbose_name='开票软件开始日期')),
                ('invoice_software_end_date', models.DateField(blank=True, db_comment='开票软件结束日期', null=True, verbose_name='开票软件结束日期')),
                ('insurance_types', models.CharField(blank=True, db_comment='参保险种', max_length=255, null=True, verbose_name='参保险种')),
                ('insured_count', models.IntegerField(blank=True, db_comment='参保人数', null=True, verbose_name='参保人数')),
                ('social_insurance_agency_fee', models.IntegerField(blank=True, db_comment='社保代理费', null=True, verbose_name='社保代理费')),
                ('social_insurance_start_date', models.DateField(blank=True, db_comment='社保开始日期', null=True, verbose_name='社保开始日期')),
                ('social_insurance_end_date', models.DateField(blank=True, db_comment='社保结束日期', null=True, verbose_name='社保结束日期')),
                ('statistical_report_fee', models.IntegerField(blank=True, db_comment='统计局报表费', null=True, verbose_name='统计局报表费')),
                ('statistical_start_date', models.DateField(blank=True, db_comment='统计开始日期', null=True, verbose_name='统计开始日期')),
                ('statistical_end_date', models.DateField(blank=True, db_comment='统计结束日期', null=True, verbose_name='统计结束日期')),
                ('change_business', models.CharField(blank=True, db_comment='变更业务', max_length=255, null=True, verbose_name='变更业务')),
                ('change_fee', models.IntegerField(blank=True, db_comment='变更收费', null=True, verbose_name='变更收费')),
                ('administrative_license', models.CharField(blank=True, db_comment='行政许可', max_length=255, null=True, verbose_name='行政许可')),
                ('administrative_license_fee', models.IntegerField(blank=True, db_comment='行政许可收费', null=True, verbose_name='行政许可收费')),
                ('other_business', models.CharField(blank=True, db_comment='其他业务', max_length=255, null=True, verbose_name='其他业务')),
                ('other_business_fee', models.IntegerField(blank=True, db_comment='其他业务收费', null=True, verbose_name='其他业务收费')),
                ('proof_of_charge', models.JSONField(blank=True, default=list, help_text='收费凭证（最多3张）', null=True, validators=[django.core.validators.MaxLengthValidator(3)], verbose_name='收费凭证')),
                ('total_fee', models.IntegerField(blank=True, db_comment='总费用', null=True, verbose_name='总费用')),
                ('submitter', models.CharField(blank=True, db_comment='提交人', max_length=100, null=True, verbose_name='提交人')),
                ('create_time', models.DateTimeField(db_comment='创建日期', default=django.utils.timezone.now, verbose_name='创建日期')),
                ('charge_date', models.DateField(blank=True, db_comment='收费日期', null=True, verbose_name='收费日期')),
                ('charge_method', models.CharField(blank=True, db_comment='收费方式', max_length=100, null=True, verbose_name='收费方式')),
                ('auditor', models.CharField(blank=True, db_comment='审核员', max_length=100, null=True, verbose_name='审核员')),
                ('audit_date', models.DateField(blank=True, db_comment='审核日期', null=True, verbose_name='审核日期')),
                ('status', models.IntegerField(choices=[(0, '未审核'), (1, '已审核'), (2, '已拒绝')], db_comment='状态：0-未审核，1-已审核，2-已拒绝', default=0, verbose_name='状态')),
                ('reject_reason', models.TextField(blank=True, db_comment='审核拒绝原因', null=True, verbose_name='拒绝原因')),
                ('remarks', models.TextField(blank=True, db_comment='备注信息', verbose_name='备注')),
            ],
            options={
                'verbose_name': '费用记录',
                'verbose_name_plural': '费用记录',
                'db_table': 'zy_expense',
            },
        ),
    ]
