# Generated by Django 5.1.1 on 2025-01-08 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_no', models.CharField(db_comment='合同编号', help_text='合同编号', max_length=50, unique=True, verbose_name='合同编号')),
                ('business_type', models.CharField(choices=[('accounting', '代理记账'), ('social', '社保代理')], db_comment='业务类型', help_text='业务类型：代理记账/社保代理', max_length=20, verbose_name='业务类型')),
                ('customer_name', models.CharField(db_comment='客户名称', help_text='客户名称', max_length=255, verbose_name='客户名称')),
                ('customer_code', models.CharField(db_comment='客户统一社会信用代码', help_text='客户统一社会信用代码', max_length=50, verbose_name='客户统一社会信用代码')),
                ('customer_address', models.CharField(db_comment='客户地址', help_text='客户地址', max_length=255, verbose_name='客户地址')),
                ('customer_phone', models.CharField(db_comment='客户电话', help_text='客户电话', max_length=20, verbose_name='客户电话')),
                ('customer_contact', models.CharField(db_comment='客户联系人', help_text='客户联系人', max_length=50, verbose_name='客户联系人')),
                ('company_name', models.CharField(db_comment='公司名称', help_text='公司名称', max_length=255, verbose_name='公司名称')),
                ('company_code', models.CharField(db_comment='公司统一社会信用代码', help_text='公司统一社会信用代码', max_length=50, verbose_name='公司统一社会信用代码')),
                ('company_address', models.CharField(db_comment='公司地址', help_text='公司地址', max_length=255, verbose_name='公司地址')),
                ('company_phone', models.CharField(db_comment='公司电话', help_text='公司电话', max_length=20, verbose_name='公司电话')),
                ('business_person', models.CharField(db_comment='业务人员', help_text='业务人员', max_length=50, verbose_name='业务人员')),
                ('amount', models.DecimalField(db_comment='合同金额', decimal_places=2, help_text='合同金额', max_digits=10, verbose_name='合同金额')),
                ('sign_date', models.DateField(db_comment='合同签订日期', help_text='合同签订日期', verbose_name='签订日期')),
                ('start_date', models.DateField(db_comment='合同开始日期', help_text='合同开始日期', verbose_name='开始日期')),
                ('expire_date', models.DateField(db_comment='合同到期日期', help_text='合同到期日期', verbose_name='到期日期')),
                ('status', models.IntegerField(choices=[(0, '未签署'), (1, '生效中'), (2, '已过期'), (3, '已作废')], db_comment='合同状态', default=0, help_text='合同状态：0未签署/1生效中/2已过期/3已作废', verbose_name='合同状态')),
                ('remark', models.TextField(blank=True, db_comment='合同备注信息', help_text='合同备注信息', null=True, verbose_name='备注')),
                ('contract_files', models.JSONField(db_comment='合同文件URL列表', default=list, help_text='合同文件URL列表', verbose_name='合同文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间', help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间', help_text='更新时间', verbose_name='更新时间')),
                ('created_by', models.ForeignKey(db_comment='创建人', help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '合同',
                'verbose_name_plural': '合同',
                'db_table': 'zy_contract',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contract_no'], name='zy_contract_contrac_c470ca_idx'), models.Index(fields=['customer_name'], name='zy_contract_custome_594340_idx'), models.Index(fields=['status'], name='zy_contract_status_8e545a_idx'), models.Index(fields=['business_type'], name='zy_contract_busines_026b24_idx')],
            },
        ),
    ]
