# Generated by Django 5.1.1 on 2025-01-08 09:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='created_by',
        ),
        migrations.AddField(
            model_name='contract',
            name='submitter',
            field=models.CharField(db_comment='提交人', default=django.utils.timezone.now, help_text='提交人', max_length=50, verbose_name='提交人'),
            preserve_default=False,
        ),
    ]
