# Generated by Django 5.1.1 on 2025-01-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_remove_contract_created_by_contract_submitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='business_type',
            field=models.CharField(choices=[('代理记账', '代理记账'), ('社保代理', '社保代理')], db_comment='业务类型', help_text='业务类型：代理记账/社保代理', max_length=20, verbose_name='业务类型'),
        ),
    ]
