# Generated by Django 5.1.1 on 2025-01-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_alter_contract_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='business_type',
            field=models.CharField(choices=[('代理记账合同', '代理记账合同'), ('社保代理合同', '社保代理合同')], db_comment='业务类型', help_text='业务类型：代理记账/社保代理', max_length=20, verbose_name='业务类型'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('未签署', '未签署'), ('生效中', '生效中'), ('已过期', '已过期'), ('已作废', '已作废')], db_comment='合同状态', default='未签署', help_text='合同状态：未签署/生效中/已过期/已作废', max_length=20, verbose_name='合同状态'),
        ),
    ]
