# Generated by Django 5.1.1 on 2024-12-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, db_comment='企业的法定名称', help_text='企业的法定名称', max_length=255, null=True, verbose_name='企业名称')),
                ('daily_contact', models.CharField(blank=True, db_comment='日常业务联系人姓名', help_text='日常业务联系人姓名', max_length=100, null=True, verbose_name='日常业务联系人')),
                ('daily_contact_phone', models.CharField(blank=True, db_comment='日常业务联系人的联系电话', help_text='日常业务联系人的联系电话', max_length=20, null=True, verbose_name='日常客户联系人电话')),
                ('sales_representative', models.CharField(blank=True, db_comment='负责该客户的业务员姓名', help_text='负责该客户的业务员姓名', max_length=100, null=True, verbose_name='业务员')),
                ('social_credit_code', models.CharField(blank=True, db_comment='企业的统一社会信用代码', help_text='企业的统一社会信用代码', max_length=18, null=True, verbose_name='统一社会信用代码')),
                ('tax_bureau', models.CharField(blank=True, db_comment='企业所属的税务分局', help_text='企业所属的税务分局', max_length=100, null=True, verbose_name='所属分局')),
                ('business_source', models.CharField(blank=True, db_comment='客户的业务来源渠道', help_text='客户的业务来源渠道', max_length=100, null=True, verbose_name='业务来源')),
                ('tax_registration_type', models.CharField(blank=True, db_comment='企业的税务登记类型', help_text='企业的税务登记类型', max_length=20, null=True, verbose_name='税务登记类型')),
                ('chief_accountant', models.CharField(blank=True, db_comment='负责该企业的主管会计姓名', help_text='负责该企业的主管会计姓名', max_length=100, null=True, verbose_name='主管会计')),
                ('responsible_accountant', models.CharField(blank=True, db_comment='负责该企业的责任会计姓名', help_text='负责该企业的责任会计姓名', max_length=100, null=True, verbose_name='责任会计')),
                ('enterprise_status', models.CharField(blank=True, db_comment='企业当前的经营状态', help_text='企业当前的经营状态', max_length=20, null=True, verbose_name='企业状态')),
                ('affiliated_enterprises', models.TextField(blank=True, db_comment='与该企业有关联的其他企业', help_text='与该企业有关联的其他企业', null=True, verbose_name='同宗企业')),
                ('main_business', models.TextField(blank=True, db_comment='企业的主要经营业务', help_text='企业的主要经营业务', null=True, verbose_name='企业主营')),
                ('boss_profile', models.TextField(blank=True, db_comment='企业老板的个人特征描述', help_text='企业老板的个人特征描述', null=True, verbose_name='老板画像')),
                ('communication_notes', models.TextField(blank=True, db_comment='与该企业沟通时需要注意的事项', help_text='与该企业沟通时需要注意的事项', null=True, verbose_name='沟通注意事项')),
                ('business_scope', models.TextField(blank=True, db_comment='企业的经营范围描述', help_text='企业的经营范围描述', null=True, verbose_name='经营范围')),
                ('business_address', models.TextField(blank=True, db_comment='企业的实际经营地址', help_text='企业的实际经营地址', null=True, verbose_name='经营地址')),
                ('registered_capital', models.DecimalField(blank=True, db_comment='企业的注册资本金额', decimal_places=0, help_text='企业的注册资本金额', max_digits=15, null=True, verbose_name='注册资本')),
                ('establishment_date', models.DateField(blank=True, db_comment='企业的成立日期', help_text='企业的成立日期', null=True, verbose_name='成立时间')),
                ('license_expiry_date', models.DateField(blank=True, db_comment='营业执照的到期日期', help_text='营业执照的到期日期', null=True, verbose_name='执照到期日')),
                ('capital_contribution_deadline', models.DateField(blank=True, db_comment='注册资本认缴的截止日期', help_text='注册资本认缴的截止日期', null=True, verbose_name='认缴到期日')),
                ('enterprise_type', models.CharField(blank=True, db_comment='企业的类型，如有限责任公司、股份有限公司等', help_text='企业的类型，如有限责任公司、股份有限公司等', max_length=100, null=True, verbose_name='企业类型')),
                ('shareholders', models.TextField(blank=True, db_comment='企业的股东信息', help_text='企业的股东信息', null=True, verbose_name='股东')),
                ('supervisors', models.TextField(blank=True, db_comment='企业的监事信息', help_text='企业的监事信息', null=True, verbose_name='监事')),
                ('annual_inspection_password', models.CharField(blank=True, db_comment='工商年检系统的登录密码', help_text='工商年检系统的登录密码', max_length=100, null=True, verbose_name='工商年检密码')),
                ('paid_in_capital', models.DecimalField(blank=True, db_comment='企业实际缴纳的注册资本金额', decimal_places=2, help_text='企业实际缴纳的注册资本金额', max_digits=15, null=True, verbose_name='实缴金额')),
                ('administrative_licenses', models.TextField(blank=True, db_comment='企业获得的行政许可信息', help_text='企业获得的行政许可信息', null=True, verbose_name='行政许可')),
                ('capital_contribution_records', models.TextField(blank=True, db_comment='企业注册资本实缴的记录', help_text='企业注册资本实缴的记录', null=True, verbose_name='实缴记录')),
                ('basic_bank', models.CharField(blank=True, db_comment='企业的基本开户银行名称', help_text='企业的基本开户银行名称', max_length=100, null=True, verbose_name='基本开户银行')),
                ('basic_bank_account', models.CharField(blank=True, db_comment='企业的基本开户银行账号', help_text='企业的基本开户银行账号', max_length=30, null=True, verbose_name='基本开户行账号')),
                ('basic_bank_number', models.CharField(blank=True, db_comment='企业基本开户银行的行号', help_text='企业基本开户银行的行号', max_length=20, null=True, verbose_name='基本开户行行号')),
                ('general_bank', models.CharField(blank=True, db_comment='企业的一般开户银行名称', help_text='企业的一般开户银行名称', max_length=100, null=True, verbose_name='一般开户行')),
                ('general_bank_account', models.CharField(blank=True, db_comment='企业的一般开户银行账号', help_text='企业的一般开户银行账号', max_length=30, null=True, verbose_name='一般开户银行账号')),
                ('general_bank_number', models.CharField(blank=True, db_comment='企业一般开户银行的行号', help_text='企业一般开户银行的行号', max_length=20, null=True, verbose_name='一般开户行行号')),
                ('has_online_banking', models.CharField(blank=True, db_comment='企业是否办理了网上银行', help_text='企业是否办理了网上银行', max_length=10, null=True, verbose_name='是否办理网银盾')),
                ('is_online_banking_custodian', models.CharField(blank=True, db_comment='企业的网银盾是否由我方托管', help_text='企业的网银盾是否由我方托管', max_length=10, null=True, verbose_name='是否网银盾托管')),
                ('legal_representative_name', models.CharField(blank=True, db_comment='企业法定代表人姓名', help_text='企业法定代表人姓名', max_length=100, null=True, verbose_name='法人姓名')),
                ('legal_representative_phone', models.CharField(blank=True, db_comment='企业法定代表人的联系电话', help_text='企业法定代表人的联系电话', max_length=20, null=True, verbose_name='法人联系人电话')),
                ('legal_representative_id', models.CharField(blank=True, db_comment='企业法定代表人的身份证号码', help_text='企业法定代表人的身份证号码', max_length=18, null=True, verbose_name='法人身份证')),
                ('legal_representative_tax_password', models.CharField(blank=True, db_comment='法定代表人的电子税务局登录密码', help_text='法定代表人的电子税务局登录密码', max_length=100, null=True, verbose_name='法人电子税务局密码')),
                ('financial_contact_name', models.CharField(blank=True, db_comment='企业财务负责人姓名', help_text='企业财务负责人姓名', max_length=100, null=True, verbose_name='财务负责人姓名')),
                ('financial_contact_phone', models.CharField(blank=True, db_comment='企业财务负责人的联系电话', help_text='企业财务负责人的联系电话', max_length=20, null=True, verbose_name='财务负责人联系电话')),
                ('financial_contact_id', models.CharField(blank=True, db_comment='企业财务负责人的身份证号码', help_text='企业财务负责人的身份证号码', max_length=18, null=True, verbose_name='财务负责人身份证')),
                ('financial_contact_tax_password', models.CharField(blank=True, db_comment='财务负责人的电子税务局登录密码', help_text='财务负责人的电子税务局登录密码', max_length=100, null=True, verbose_name='财务负责人电子税务局密码')),
                ('tax_officer_name', models.CharField(blank=True, db_comment='企业办税员姓名', help_text='企业办税员姓名', max_length=100, null=True, verbose_name='办税员姓名')),
                ('tax_officer_phone', models.CharField(blank=True, db_comment='企业办税员的联系电话', help_text='企业办税员的联系电话', max_length=20, null=True, verbose_name='办税员联系电话')),
                ('tax_officer_id', models.CharField(blank=True, db_comment='企业办税员的身份证号码', help_text='企业办税员的身份证号码', max_length=18, null=True, verbose_name='办税员身份证')),
                ('tax_officer_tax_password', models.CharField(blank=True, db_comment='办税员的电子税务局登录密码', help_text='办税员的电子税务局登录密码', max_length=100, null=True, verbose_name='办税员电子税务局密码')),
                ('tripartite_agreement_account', models.CharField(blank=True, db_comment='用于税费扣缴的三方协议账户', help_text='用于税费扣缴的三方协议账户', max_length=30, null=True, verbose_name='三方协议账户')),
                ('tax_categories', models.TextField(blank=True, db_comment='企业需要缴纳的税种', help_text='企业需要缴纳的税种', null=True, verbose_name='税种')),
                ('personal_income_tax_staff', models.TextField(blank=True, db_comment='需要申报个人所得税的员工信息', help_text='需要申报个人所得税的员工信息', null=True, verbose_name='申报个税人员')),
                ('personal_income_tax_password', models.CharField(blank=True, db_comment='个人所得税申报系统的登录密码', help_text='个人所得税申报系统的登录密码', max_length=100, null=True, verbose_name='个税密码')),
                ('legal_person_id_images', models.JSONField(db_comment='法定代表人身份证的扫描件或照片地址', default=list, help_text='法定代表人身份证的扫描件或照片地址', verbose_name='法人身份证图片')),
                ('other_id_images', models.JSONField(db_comment='其他相关人员身份证的扫描件或照片地址', default=list, help_text='其他相关人员身份证的扫描件或照片地址', verbose_name='其他身份证图片')),
                ('business_license_images', models.JSONField(db_comment='企业营业执照的扫描件或照片地址', default=list, help_text='企业营业执照的扫描件或照片地址', verbose_name='营业执照图片')),
                ('bank_account_license_images', models.JSONField(db_comment='企业开户许可证的扫描件或照片地址', default=list, help_text='企业开户许可证的扫描件或照片地址', verbose_name='开户许可图片')),
                ('supplementary_images', models.JSONField(db_comment='其他补充的扫描件或照片地址', default=list, help_text='其他补充的扫描件或照片地址', verbose_name='补充图片')),
                ('update_time', models.DateTimeField(auto_now=True, db_comment='记录的最后更新时间', help_text='记录的最后更新时间', null=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_comment='记录的创建时间', help_text='记录的创建时间', null=True, verbose_name='创建时间')),
                ('submitter', models.CharField(blank=True, db_comment='创建或最后修改该记录的用户', help_text='创建或最后修改该记录的用户', max_length=100, null=True, verbose_name='提交人')),
                ('business_status', models.CharField(blank=True, db_comment='当前业务的状态', default='ongoing', help_text='当前业务的状态', max_length=20, null=True, verbose_name='业务状态')),
                ('boss_name', models.CharField(blank=True, db_comment='企业老板的姓名', help_text='企业老板的姓名', max_length=100, null=True, verbose_name='老板名称')),
            ],
            options={
                'verbose_name': '客户信息',
                'verbose_name_plural': '客户信息',
                'db_table': 'zy_customer',
            },
        ),
    ]
